'use strict'

export const SET_COMPANIES = 'SET_COMPANIES'

export const SET_APP_LOADING = 'SET_APP_LOADING'

export const UPDATE_LOCATION = 'UPDATE_LOCATION'

export const UPDATE_TRADE = 'UPDATE_TRADE'

export const UPDATE_COMPANY_NAME = 'UPDATE_COMPANY_NAME'
